apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  namespace: api-server
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: api-server
  type: ClusterIP
status:
  loadBalancer: {}